#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Generate build/generated/contributors.h from git history

set -euo pipefail

OUTDIR="${BUILD_DIR:-build}/generated"
OUTFILE="$OUTDIR/contributors.h"
TMPFILE="$(mktemp)"

trap 'rm -f "$TMPFILE"' EXIT

mkdir -p "$OUTDIR"

# Get unique contributor names, excluding bots and invalid entries
# In Docker cross-compile environments, git may not be available — use
# the existing generated file from build/generated/ as a fallback.
if command -v git >/dev/null 2>&1 && git -c safe.directory='*' rev-parse --git-dir >/dev/null 2>&1; then
    contributors=$(git -c safe.directory='*' log --format='%aN' | sort -u \
        | grep -ivE 'bot\b|\[bot\]|dependabot|github-actions|claude' \
        | awk 'length >= 2' || true)
elif [ -f "build/generated/contributors.h" ] && [ "$OUTDIR" != "build/generated" ]; then
    # No git — copy from host-generated file if available
    mkdir -p "$OUTDIR"
    cp "build/generated/contributors.h" "$OUTFILE"
    echo "Copied $OUTFILE from build/generated/"
    exit 0
else
    # No git and no fallback — generate empty list
    contributors=""
fi

# Generate the header into a temp file
{
    echo "// SPDX-License-Identifier: GPL-3.0-or-later"
    echo "// Auto-generated by gen-contributors.sh — do not edit"
    echo "#pragma once"
    echo ""
    echo "inline constexpr const char* kContributors[] = {"
    while IFS= read -r name; do
        [ -z "$name" ] && continue
        # Escape any double quotes in names
        escaped=$(printf '%s' "$name" | sed 's/"/\\"/g')
        echo "    \"$escaped\","
    done <<< "$contributors"
    echo "};"
    echo ""
    echo "inline constexpr int kContributorCount = sizeof(kContributors) / sizeof(kContributors[0]);"
} > "$TMPFILE"

# Only update if content changed
if [ -f "$OUTFILE" ] && diff -q "$TMPFILE" "$OUTFILE" >/dev/null 2>&1; then
    exit 0
fi

cp "$TMPFILE" "$OUTFILE"
echo "Generated $OUTFILE"
